# Generated by Django 5.2.8 on 2026-03-03 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
    ]
