# Generated by Django 5.2.8 on 2026-03-04 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_liveclass_recordedreplay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liveclass',
            options={'ordering': ['-scheduled_at']},
        ),
        migrations.RemoveField(
            model_name='liveclass',
            name='youtube_video_id',
        ),
    ]
